"""Initial migration for bands, venues, and concerts

Revision ID: e1a50d0544c4
Revises: 
Create Date: 2024-09-17 17:17:22.915576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a50d0544c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bands', sa.Column('name', sa.String(), nullable=True))
    op.add_column('bands', sa.Column('hometown', sa.String(), nullable=True))
    op.alter_column('bands', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('bands', 'Name')
    op.drop_column('bands', 'Hometown')
    op.add_column('venues', sa.Column('title', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('city', sa.String(), nullable=True))
    op.alter_column('venues', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('venues', 'Tiltle')
    op.drop_column('venues', 'City')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('City', sa.NUMERIC(), nullable=True))
    op.add_column('venues', sa.Column('Tiltle', sa.NUMERIC(), nullable=True))
    op.alter_column('venues', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'title')
    op.add_column('bands', sa.Column('Hometown', sa.NUMERIC(), nullable=True))
    op.add_column('bands', sa.Column('Name', sa.NUMERIC(), nullable=True))
    op.alter_column('bands', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('bands', 'hometown')
    op.drop_column('bands', 'name')
    op.drop_table('concerts')
    # ### end Alembic commands ###
